# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=3.0.0
group=com.cursee.automessage
java_version=17

# Common
minecraft_version=1.20.1
mod_name=AutoMessage
mod_author=Lupin, Jason13
mod_id=automessage
license=Unlicense
credits=Thanks to Jared(MultiLoader-Template), Darkhax(Bookshelf), Serilum(Collective) and PacifistMC(Forgix).
description=Send automated messages to your players.
minecraft_version_range=[1.20, 1.20.2)
fabric_minecraft_version_range=>=1.20 <1.20.2
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.90.0+1.20.1
fabric_loader_version=0.16.10

# Forge
forge_version=47.0.0
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
